language: csharp
os: osx
mono: none
dotnet: 2.1.300
dist: xenial

install:
- dotnet restore

branches:
  only:
  - master

script:
- dotnet build
- dotnet test BestinClass.xUnitTest/BestinClass.xUnitTest.csproj